name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ${{ secrets.TEST }}

      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ${{ secrets }}

      - uses: actions/checkout@v3
      - name: Create file
        run: echo "Asd" >> test

      - uses: actions/checkout@v3
      - name: Show file
        run: cat test
